apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ah3jlxodp-java-springboot
  janus-idp.io/tekton: ah3jlxodp-java-springboot
  backstage.io/kubernetes-id: ah3jlxodp-java-springboot
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ah3jlxodp-java-springboot
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
