apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ah3jlxodp-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ah3jlxodp-java-springboot-gitops